uploads = []
generated = []

[[outputs]]
id = "H4eZt2d-Wk3n1pBRYLTTf"
uri = "file://banana-protector.zip"
type = "unspecified"
title = "banana-protector.zip"

[[outputs]]
id = "z57kKWm0xhR8r7rFJlNuz"
uri = "file://banana-protector-v2.zip"
type = "unspecified"
title = "Banana Protector v2 - Bot + API"

[[outputs]]
id = "vbhhy7JpdCW6SzQHW9epT"
uri = "file://banana-standalone-v2.zip"
type = "unspecified"
title = "Banana Protector Standalone v2 — obfuscador actualizado"

[[outputs]]
id = "svpjww5pS7NQJkeMN1LMz"
uri = "file://banana-railway-ready.zip"
type = "unspecified"
title = "Banana Protector — listo para Railway"

[[outputs]]
id = "vPG6VZsGB4joinQ3pmk8P"
uri = "file://banana-render-ready.zip"
type = "unspecified"
title = "Banana Protector — Render listo (obfuscator.js corregido)"
